name: docs

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/static_code_checks.yaml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/unit_tests.yaml
      - .github/workflows/integration_tests.yaml
      - '**.py'
      - '**.ipynb'
      - poetry.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: 'true'
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.10'
          cache: 'poetry'
      - run: |
          python3 -m pip install --upgrade pip && python3 -m pip install poetry
          poetry env use '3.10'
          source $(poetry env info --path)/bin/activate
          poetry install --with docs,test
          cd docs && rm -rf source/reference/api/_autosummary && make html
          cd .. && coverage run -m pytest florist/tests/unit && coverage xml && coverage report -m
#
#      - name: Upload coverage to Codecov
#        uses: Wandalen/wretry.action@v1.4.4
#        with:
#          action: codecov/codecov-action@v4.0.1
#          with: |
#            token: ${{ secrets.CODECOV_TOKEN }}
#            file: ./coverage.xml
#            name: codecov-umbrella
#            fail_ci_if_error: true
#          attempt_limit: 5
#          attempt_delay: 30000
#
      - name: Deploy to Github pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: github_pages
          folder: docs/build/html
