name: docs (build)

on:
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/docs_build.yml
      - '**.py'
      - '**.ipynb'
      - poetry.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: |
          python3 -m pip install --upgrade pip && python3 -m pip install poetry
          poetry env use '3.9'
          source .venv/bin/activate
          poetry install --with docs,test
          cd docs && rm -rf source/reference/api/_autosummary && make html
          cd .. && coverage run -m pytest florist/tests/unit && coverage xml && coverage report -m
#      - name: Upload coverage to Codecov
#        uses: Wandalen/wretry.action@v1.4.4
#        with:
#          action: codecov/codecov-action@v4.0.1
#          with: |
#            token: ${{ secrets.CODECOV_TOKEN }}
#            file: ./coverage.xml
#            name: codecov-umbrella
#            fail_ci_if_error: true
#          attempt_limit: 5
#          attempt_delay: 30000
