name: integration-tests

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/static_code_checks.yml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/tests.yml
      - '**.py'
      - '**.ipynb'
      - poetry.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/static_code_checks.yml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/tests.yml
      - '**.py'
      - '**.ipynb'
      - poetry.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: '3.10'
      - name: Setup redis
        uses: supercharge/redis-github-action@1.8.0
        with:
          redis-version: 7.2.4
      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: 7.0.8
      - name: Install dependencies and check code
        run: |
          poetry env use '3.9'
          source .venv/bin/activate
          poetry install --with docs,test
          coverage run -m pytest florist/tests/integration && coverage xml && coverage report -m
      - name: Upload python coverage to Codecov
        uses: Wandalen/wretry.action@v3.5.0
        with:
          action: codecov/codecov-action@v4.0.1
          with: |
            token: ${{ secrets.CODECOV_TOKEN }}
            name: codecov-umbrella
            fail_ci_if_error: true
            verbose: true
          attempt_limit: 5
          attempt_delay: 30000

#      TODO enable this once we have integration tests for the UI
#      - name: Setup yarn
#        uses: mskelton/setup-yarn@v1
#      - name: Install nextjs dependencies and check code
#        run: |
#          yarn
#          yarn integration-test
#      - name: Upload js coverage to Codecov
#        uses: Wandalen/wretry.action@v3.5.0
#        with:
#          action: codecov/codecov-action@v4.0.1
#          with: |
#            token: ${{ secrets.CODECOV_TOKEN }}
#            name: codecov-umbrella
#            fail_ci_if_error: true
#            verbose: true
#          attempt_limit: 5
#          attempt_delay: 30000
