name: integration-tests

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/static_code_checks.yaml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/unit_tests.yaml
      - .github/workflows/integration_tests.yaml
      - '**.py'
      - '**.ipynb'
      - poetry.lock
      - pyproject.toml
      - yarn.lock
      - '**.rst'
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/static_code_checks.yaml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/unit_tests.yaml
      - .github/workflows/integration_tests.yaml
      - '**.py'
      - '**.ipynb'
      - poetry.lock
      - pyproject.toml
      - yarn.lock
      - '**.rst'
      - '**.md'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
      - name: Set up Python 3.10
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          version: 1.7.1
      - name: Setup redis
        uses: supercharge/redis-github-action@1.8.0
        with:
          redis-version: 7.2.4
      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: 7.0.8
      - name: Install dependencies and check code
        run: |
          python -m pip install --upgrade pip
          poetry env use python3.10
          source .venv/bin/activate
          poetry install --with docs,test
          coverage run -m pytest florist/tests/integration && coverage xml && coverage report -m
      - name: Upload python coverage to Codecov
        uses: Wandalen/wretry.action@v3.8.0
        with:
          action: codecov/codecov-action@v4.6.0
          with: |
            token: ${{ secrets.CODECOV_TOKEN }}
            name: codecov-umbrella
            fail_ci_if_error: true
          attempt_limit: 5
          attempt_delay: 30000

#      TODO enable this once we have integration tests for the UI
#
#      - name: Setup yarn
#        uses: mskelton/setup-yarn@v1
#      - name: Install nextjs dependencies and check code
#        run: |
#          yarn
#          yarn integration-test
#      - name: Upload js coverage to Codecov
#        uses: Wandalen/wretry.action@v3.8.0
#        with:
#          action: codecov/codecov-action@v4.0.1
#          with: |
#            token: ${{ secrets.CODECOV_TOKEN }}
#            name: codecov-umbrella
#            fail_ci_if_error: true
#            verbose: true
#          attempt_limit: 5
#          attempt_delay: 30000
