name: unit-tests

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/static_code_checks.yaml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/unit_tests.yaml
      - .github/workflows/integration_tests.yaml
      - '**.py'
      - '**.ipynb'
      - '**.tsx'
      - poetry.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/static_code_checks.yaml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/unit_tests.yaml
      - .github/workflows/integration_tests.yaml
      - '**.py'
      - '**.ipynb'
      - '**.tsx'
      - poetry.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'
      - name: Install python dependencies and check code
        run: |
          poetry env use '3.9'
          source .venv/bin/activate
          poetry install --with docs,test
          coverage run -m pytest florist/tests/unit && coverage xml && coverage report -m
      - name: Upload python coverage to Codecov
        uses: Wandalen/wretry.action@v3.5.0
        with:
          action: codecov/codecov-action@v4.0.1
          with: |
            token: ${{ secrets.CODECOV_TOKEN }}
            name: codecov-umbrella
            fail_ci_if_error: true
            verbose: true
          attempt_limit: 5
          attempt_delay: 30000
      - name: Setup yarn
        uses: mskelton/setup-yarn@v3
      - name: Install nextjs dependencies and check code
        run: |
          yarn
          yarn unit-test
      - name: Upload js coverage to Codecov
        uses: Wandalen/wretry.action@v3.5.0
        with:
          action: codecov/codecov-action@v4.0.1
          with: |
            token: ${{ secrets.CODECOV_TOKEN }}
            name: codecov-umbrella
            fail_ci_if_error: true
            verbose: true
          attempt_limit: 5
          attempt_delay: 30000
