name: unit-tests

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/static_code_checks.yml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/tests.yml
      - '**.py'
      - '**.ipynb'
      - poetry.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/static_code_checks.yml
      - .github/workflows/docs_build.yml
      - .github/workflows/docs_deploy.yml
      - .github/workflows/tests.yml
      - '**.py'
      - '**.ipynb'
      - poetry.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Install poetry
        run: python3 -m pip install --upgrade pip && python3 -m pip install poetry
      - uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.9'
          cache: 'poetry'
      - name: Install python dependencies and check code
        run: |
          poetry env use '3.9'
          source $(poetry env info --path)/bin/activate
          poetry install --with docs,test
          coverage run -m pytest florist/tests/unit && coverage xml && coverage report -m
      - name: Upload python coverage to Codecov
        uses: Wandalen/wretry.action@v1.4.4
        with:
          action: codecov/codecov-action@v4.0.1
          with: |
            token: ${{ secrets.CODECOV_TOKEN }}
            name: codecov-umbrella
            fail_ci_if_error: true
          attempt_limit: 5
          attempt_delay: 30000
      - name: Setup yarn
        uses: mskelton/setup-yarn@v1
      - name: Install nextjs dependencies and check code
        run: |
          yarn
          yarn unit-test
      - name: Upload js coverage to Codecov
        uses: Wandalen/wretry.action@v1.4.4
        with:
          action: codecov/codecov-action@v4.0.1
          with: |
            token: ${{ secrets.CODECOV_TOKEN }}
            name: codecov-umbrella
            fail_ci_if_error: true
          attempt_limit: 5
          attempt_delay: 30000
